### ISSUE TITLE
Not stable builds

### ISSUE THREAD

**Issue by sashuk** [sashuk/vidi#144]
One or more tests randomly break down during Travis CI builds

**Comment by sashuk** [comment]
There were 5 build attempted on the same code base, 3 of them failed. For now there could be two reasons:
- weak TravisCI virtual environment (increase timeouts in `puppeteer` tests)
- unstable staging infrastructure (log console in all `puppeteer` tests and analyze it)

**Comment by sashuk** [comment]
Results of running tests on **local** machine on the **same codebase** below show that the problem is not in the CI, but in the test running process itself, keep investigating further.

```

##############################################################################################
Run 1
 1) Draw
       should allow drawing features and restoring them switching base layers:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.it (test/puppeteer/draw.test.js:74:95)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Layer tree filters
       should store filters in state snapshot:
     Error: No node found for selector: [href="#state-snapshots-dialog-content-content"]
      at assert (node_modules/puppeteer/lib/helper.js:270:11)
      at Frame.click (node_modules/puppeteer/lib/FrameManager.js:611:5)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

##############################################################################################
Run 2
1) Editor
       (if user is authorized)
         should add, update and delete features:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.it (test/puppeteer/editor.test.js:73:80)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) Layer tree filters
       should store filters in state snapshot:
     Error: No node found for selector: [href="#state-snapshots-dialog-content-content"]
      at assert (node_modules/puppeteer/lib/helper.js:270:11)
      at Frame.click (node_modules/puppeteer/lib/FrameManager.js:611:5)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) State snapshots
       should restore multiple snapshots with initial and dynamic layers in URL:

      AssertionError: expected true to be false
      + expected - actual

      -true
      +false

      at Context.it (test/puppeteer/stateSnapshots.test.js:332:151)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

##############################################################################################
Run 3
 1) Layer tree filters
       should store filters in state snapshot:
     Error: No node found for selector: [href="#state-snapshots-dialog-content-content"]
      at assert (node_modules/puppeteer/lib/helper.js:270:11)
      at Frame.click (node_modules/puppeteer/lib/FrameManager.js:611:5)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) OfflineMap
       should make the map area available offline:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

##############################################################################################
Run 4

1) Layer tree filters
       should store filters in state snapshot:
     Error: No node found for selector: [href="#state-snapshots-dialog-content-content"]
      at assert (node_modules/puppeteer/lib/helper.js:270:11)
      at Frame.click (node_modules/puppeteer/lib/FrameManager.js:611:5)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by sashuk** [comment]
Overall the mechanism of detecting the page load was changed, which brought stability and lesser build time

The whole test set is built successfully: https://travis-ci.org/sashuk/vidi
